### ISSUE TITLE
Webpack Usage?

### ISSUE THREAD

**Issue by zevisert** [microsoft/vscode-oniguruma#10]
I'm trying to bundle my extension into a single file, as [recommended by the vscode extension docs](https://code.visualstudio.com/api/working-with-extensions/bundling-extension).

I'm running into problems with this library's requirement of calling `loadWASM` to instantiate a wasm module. I can already use webpack 5's built-in wasm module loader, but there's no way for me to provide an instantiated wasm module back to this library.

It would be great if I could set `onigBinding` myself.

**Comment by zevisert** [comment]
Or better yet, it would be great to be able to pass my own `WASMLoader`; then regardless of how consumers of this package are bundling, they always have a way to provide their own `WebAssembly.WebAssemblyInstantiatedSource`, even if it's just by `Promise.resolve`.

**Comment by alexdima** [comment]
The idea of `loadWASM` was that the embedder can control how they want to load the WASM. Either by passing in an `ArrayBuffer` or a browser `Response` for streaming compilation of the WASM. 

If that is not sufficient and you want to allow passing in a `WASMLoader` (`(importObject: Record<string, Record<string, WebAssembly.ImportValue>> | undefined) => Promise<WebAssembly.WebAssemblyInstantiatedSource>`), then PR welcome. It can probably be added as an optional in the `IOptions`

**Comment by zevisert** [comment]
I think that'd work great, I'll come up with a PR in the next few days!

**Comment by SNDST00M** [comment]
Could someone kindly clarify how to get the URL to `onig.wasm`?

**Comment by M00TSDNS** [comment]
^ Solved that with [this](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/blob/v1.0.0-rc-1/src/util/oniguruma.ts) code and [this](https://gitlab.com/SNDST00M/vscode-textmate-languageservice/-/blob/v1.0.0-rc-1/src/util/loader.ts) loader that is admittedly too document-oriented.

It's amusing now that I found this ticket before ...
I want browser support and also Webpack. Could I get a link to your Webpack config to help me out?

**Comment by M00TSDNS** [comment]
A working `webpack`+`typescript` config if one cannot use fetch or import the wasm - https://github.com/zikaari/onigasm/issues/2#issuecomment-1427077087.

**Comment by RedCMD** [comment]
I was able to load the `.wasm` file using VSCode's built-in file system manager

```ts
const uri = vscode.Uri.joinPath(context.extensionUri, 'node_modules', 'vscode-oniguruma', 'release', 'onig.wasm');
const wasm = await vscode.workspace.fs.readFile(uri);
const options: vscodeOniguruma.IDataOptions = {
	data: wasm,
	print(string: string) {
		console.log(string);
	}
}
await vscodeOniguruma.loadWASM(options);
```

(make sure the node module is packaged in the extension. or just copy the `onig.wasm` file)
```json
"dependencies": { "vscode-oniguruma": "1.7.0" }
```
