### ISSUE TITLE
Some way of detecting if already loaded

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/vscode-oniguruma#6]
Hello

I am using this in my vscode extension, but since VSCode also loads this module, calling oniguruma.loadWASM(); will throw an exception.

I could do a try/catch around this, but it's ugly. Maybe some loaded variable could be exposed? Or accept a bool to be silent and not throw an exception

**Comment by alexdima** [comment]
@CoenraadS Do you mean to remove the throw statement from here? -- https://github.com/microsoft/vscode-oniguruma/blob/a2345d7fa36529cffaee10ecaed0f85b9dc7a1f4/src/index.ts#L374-L380

**Comment by CoenraadS** [comment]
Yes
